import pandas as pd
from pandas import *
import csv

df = pd.read_excel('mkt.xlsx')

df = df.drop(columns=['MAKE','FRACPERCENTOWNED', 'FRACPURCHASEDATE', 'COMPEMAIL', 'COMPCOUNTRY',
'CONTACTEMAIL', 'COMPALTNAME', 'COMPWEBADDRESS', 'COMPADDRESS1','COMPADDRESS2', 'COMPCITY', 'COMPSTATE',
'COMPSTATEABBR', 'COMPZIPCODE', 'COMPOFFICE', 'COMPFAX','COMPMOBILE','CONTACTPREFIX', 'CONTACTFIRSTNAME',
'CONTACTMI', 'CONTACTLASTNAME', 'CONTACTSUFFIX', 'CONTACTTITLE', 'CONTACTOFFICE', 'CONTACTFAX', 'CONTACTMOBILE',
'BASEIATA', 'BASEICAO', 'BASENAME', 'BASECITY', 'BASESTATE', 'ACID', 'COMPID', 'CONTACTID'])

df = df[['MODEL', 'YEARMFR', 'YEARDLV', 'SERIALNBR', 'REGNBR', 'STATUS',	'ASKING',
'ASKINGAMT', 'AFTT', 'ENG1TT',	'ENG2TT','ENG3TT', 'ENG4TT', 'SMOH1', 'SMOH2',
'SMOH3', 'SMOH4','BASESTATEABBR', 'BASECOUNTRY', 'COMPANY', 'RELATION', 'DATELISTED',
'PURCHASEDATE']]

df = df.loc[(df['RELATION'] == 'Owner')]

df = df.loc[(df['STATUS'] == 'For Sale')]

df = df.to_excel('MktRpt.xlsx')

print(df)